apiVersion: v1
description: Apache Kafka is publish-subscribe messaging rethought as a distributed
  commit log.
home: https://kafka.apache.org/
icon: https://kafka.apache.org/images/logo.png
keywords:
- kafka
- zookeeper
- kafka petset
maintainers:
- email: gardner.vickers@onyxplatform.org
  name: Gardner Vickers
name: kafka
sources:
- https://github.com/kubernetes/charts/tree/master/incubator/zookeeper
- https://github.com/Yolean/kubernetes-kafka
- https://github.com/solsson/dockerfiles/tree/master/kafka
version: 0.1.1
